#!/bin/bash

xdg_configs=( nvim i3 sway i3status i3status-rust dunst kitty ranger
    pulseaudio-ctl polybar conky geoclue zathura dmenu-recent btop ncmpcpp mpd
    neofetch morc_menu qutebrowser picom.conf redshift.conf shalarm vimiv
    starship.toml tbsm wezterm swaylock waybar mako gtk-3.0 goneovim )
configs=( .zshrc .zprofile .profile .gitconfig .goldendict .Xresources .dmenurc
    .dir_colors .fonts .dircolors .zplug .backgrounds .antigen )
scripts=( brave-popup simplescrot shalarm i3lock-color switch_ibus_engine
    switch_brightness my_dmenu_recency sway-prop import-gsettings )

src=$(pwd)
xdg_config_src=$src/.config
config_src=$src
script_src=$src/script

xdg_config_out=~/.config
config_out=~
script_out=~/.local/bin

uninstall_configs() {
  for i in ${configs[@]}; do
    rm -rf "$config_out/$i"
  done

  for i in ${xdg_configs[@]}; do
    rm -rf "$xdg_config_out/$i"
  done
}

uninstall_scripts() {
  for i in ${scripts[@]}; do
    rm -rf "$script_out/$i"
  done
}

install_configs() {
  for i in ${configs[@]}; do
    ln -snf "$config_src/$i" "$config_out/$i"
  done

  mkdir -p "$xdg_config_out/"
  for i in ${xdg_configs[@]}; do
    ln -snf "$xdg_config_src/$i" "$xdg_config_out/$i"
  done
}

install_scripts() {
  mkdir -p "$script_out/"
  for i in ${scripts[@]}; do
    chmod +x "$script_src/$i"
    ln -snf "$script_src/$i" "$script_out/$i"
  done
}

install_theme() {
    theme_out=~/.local/share/themes
    mkdir -p "$theme_out"
    ln -snf "$src/themes/dracula" "$theme_out/Dracula"
    icon_out=~/.local/share/icons
    mkdir -p "$icon_out"
    ln -snf "$src/themes/dracula/kde/cursors/Dracula-cursors" "$icon_out/Dracula-cursors"
    kvantum_out=~/.config/Kvantum/
    mkdir -p "$kvantum_out"
    ln -snf "$src/themes/dracula/kde/kvantum/Dracula-purple-solid" "$kvantum_out/Dracula-purple-solid"
}

uninstall_theme() {
    theme_out=~/.local/share/themes
    icon_out=~/.local/share/icons
    kvantum_out=~/.local/share/icons
    rm -rf "$theme_out/Dracula"
    rm -rf "$icon_out/Dracula-cursors"
    rm -rf "$kvantum_out/Dracula-purple-solid"
}

process_install() {
  process_uninstall
  echo "Installing config..."
  install_scripts
  install_configs
  install_theme
  echo "Install complete"
}

process_uninstall() {
  echo "Uninstalling config..."
  uninstall_scripts
  uninstall_configs
  uninstall_theme
  echo "Uninstall complete"
}

process_help() {
  echo "A script to setup config."
  echo
  echo "Syntax: configsetup [-i|u|h]"
  echo "options:"
  echo "i     Install config."
  echo "u     Uninstall config."
  echo "h     Print this Help."
  echo
}

if [[ "$#" -eq 0 ]]; then
  process_help
  exit 0
fi

while getopts ":hiu" option; do
  case $option in
    h) # display HELP
      process_help
      exit 0;;
    i) # install config
      process_install
      exit 0;;
    u) # uninstall config
      process_uninstall
      exit 0;;
    \?) # invalid option
      echo "Error: Invalid option"
      exit 1;;
  esac
done
