[theme]
name = "dracula"
# [theme.overrides]
# separator = "|"
# separator_bg = "#282a36"
# separator_fg = "#f8f8f2"
[icons]
name = "awesome"


# [[block]]
# block = "temperature"
# collapsed = false
# interval = 10
# format = "{average:1}C"
# interval = 1
# chip = "*-isa-*"
# inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "net"
icons_format = " {icon}"
format_alt = " {ip}"
format = "{speed_down}{speed_up}"
interval = 1
# device = "wlp82s0"
[block.theme_overrides]
idle_bg = "#44475a"
idle_fg = "#f8f8f2"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
interval = 20
unit = "GB"
format = "{icon} {available:1}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used:1}/{mem_total:1}({mem_used_percents:1})"
format_swap = "{swap_used:1}/{swap_total:1}({swap_used_percents:1})"
# icons_format = ""
# format_mem = " \uf2db {mem_used_percents:1}"
# format_swap = " \uf2db T:{mem_total_used_percents:1} C:{cached_percent:1} B:{buffers_percent:1}"
[block.theme_overrides]
idle_bg = "#44475a"
idle_fg = "#f8f8f2"

[[block]]
block = "cpu"
interval = 1
format = "{utilization:1}"
on_click = "kitty --class floating -e btop"

[[block]]
block = "backlight"
# device = "intel_backlight"
icons_format = "{icon}"
format = "{brightness:1}"
invert_icons = true
minimum = 15
maximum = 100
cycle = [100, 30, 0, 30]
on_click = "xfce4-power-manager -c"
[block.theme_overrides]
idle_bg = "#44475a"
idle_fg = "#f8f8f2"


[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_format = " {percentage}"
on_click = "xfce4-power-manager -c"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
player = "mpd"
format = "{title}"
hide_when_empty = true
smart_trim = true
marquee_interval = 5
max_width = 10
on_click = "kitty --class floating -e ncmpcpp"
[block.theme_overrides]
idle_bg = "#44475a"
idle_fg = "#f8f8f2"
info_bg = "#BD93F9"
info_fg = "#282A36"

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol"
format = "{volume}"
headphones_indicator = true

[[block]]
block = "time"
interval = 60
icons_format = ""
on_click = "kitty --class floating --hold -e cal -S -n 5"
# format = "%a %D/% %r"
format = " %a, %d \uf017 %H:%M"
[block.theme_overrides]
# idle_bg = "#BD93F9"
# idle_fg = "#000000"
idle_bg = "#44475a"
idle_fg = "#f8f8f2"
