#!/bin/bash
set -eu

alpha='dd'
base03='#002b36'
base02='#261E32'
base01='#586e75'
base00='#657b83'
base0='#839496'
base1='#93a1a1'
base2='#eee8d5'
base3='#fdf6e3'
yellow='#F4F99D'
orange='#FF6E67'
red='#FF6E67'
magenta='#FF92D0'
violet='#CAA9FA'
blue='#CAA9FA'
cyan='#9AEDFE'
green='#5AF78E'
font='Noto Sans'


# lock the screen
i3lock \
  --insidever-color=$base02$alpha \
  --insidewrong-color=$base02$alpha \
  --inside-color=$base02$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$magenta$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$base01$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --layout-color=$blue \
  --date-color=$blue \
  --time-color=$blue \
  --clock \
  --blur=5 \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%A, %Y-%m-%d" \
  --verif-text="Verifying..." \
  --wrong-text="Auth Failed" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --time-font=$font \
  --date-font=$font \
  --layout-font=$font \
  --verif-font=$font \
  --wrong-font=$font \
  --radius=150 \
  --ring-width=20 \
  --time-size=50 \
  --date-size=20 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
  --ignore-empty-password $@

# sleep 1 adds a small delay to prevent possible race conditions with suspend
#sleep 1

exit 0
